camunda:
  bpm:
    table-prefix: camunda.
    run:
      cors:
        allowed-origins: '*'
        enabled: 'true'
    schema-update: 'true'
    admin-user:
      id: demo
      password: demo
      firstName: Demo
    filter:
      create: All tasks

spring:
  jpa:
    open-in-view: 'true'
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5433/postgres
    password: 'admin123'
mybatis:
  mapper-locations: classpath*:/mapper/**/*Mapper.xml
  configuration:
    jdbc-type-for-null: 'NULL'
logging:
  level:
    sample:
      mybatis:
        mapper: TRACE

card:
  process:
    service: http://localhost:8080/api/process